name: repo sync

on: 
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        persist-credentials: true
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      env:
        GITHUB_TOKEN: ${{ github.token }}
      with:
        source_repo: "https://github.com/Azure/Azure-Sentinel"
        source_branch: "*"
        destination_branch: "*"
